[package]
name = "reversi-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.26", features = ["derive"] }
rayon = "1.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = { version = "3.0.0-rc5", features = ["json"] }
